### PR TITLE
Fix typos and other textual errors 

### PR DESCRIPTION
**Pull request by zhedar**
As I stumbled upon a minor typo in the documentation I thought I could read through it once and may correct some of the things I will find.
I'm currently halfway through the layout section, so **I don't recommend to merge this at the moment.** I wouldn't want to open another PR for the same reason atm.

There are several copy / paste related errors, so I decided to group them into single commits. That way they won't take that much time to review.

### CODE REVIEW

**Comment by stephanrauh** [comment]
+1! Please note that the errors of the *Attributes.xhtml files are also in our DSL file (https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/xtext/BootsFaces.jsfdsl). We try to generate as much documentation as possible.

**Comment by zhedar** [comment]
I will probably group all the changes in *attributes files in single commits like I already did, so I can correct all of them at once, when I'm done. However getting through this, takes a while :)
Or did you mean, that the *Attributes.xhtml are automatically generated from the dsl files as well? Then fixing the .xhtml files itself and then making changes again wouldn't make that much sense, I guess.

**Comment by stephanrauh** [comment]
Yes, we edit the bootsfaces.jsfdsl file to generate the *Attributes.xhtml files. We need the same text for the Javadoc comments and for the documentation in the showcase, so it's nice to write it once and generate it three times (Javadoc of the getter, Javadoc of the setter and the *Attributes.xhtml file itself).

**Comment by stephanrauh** [comment]
BTW, here's an instruction how to install the XText plugin: https://github.com/TheCoder4eu/BootsFaces-OSP/pull/296 (starting with my comment of February 20, 2016).

**Comment by zhedar** [comment]
I think I'm done with skimming for now and will look into the dsl file soon to incorporate the proposed changes in the *Attributes.
I'm sure I've overseen some little mistakes, but I'm at least happy with the PR now :)

**Comment by stephanrauh** [comment]
Thanks for your magnificent work! 75 files changed - whow!

**Pull request merged**
