### PR TITLE
Added doc on severity attribute for growl and messages component

### PR DESCRIPTION
**Pull request by jepsar**
Please fill in the version at `<b:badge value="since TODO" />`

### CODE REVIEW

**Comment by stephanrauh** [comment]
I've set the version to 1.1.2 and slightly edited your text. I hope you like the edit. (If not, just tell me).

If you've got some spare time, would you like to add the demo you've described in the text: showing infos as growls and errors as `b:messages`?

**Comment by stephanrauh** [comment]
BTW: I wonder if the change makes sense for the (singular) <code>b:message</code>, too. What's your opinion?

**Comment by jepsar** [comment]
The edit is an improvement. The library is still at `1.1.1-SNAPSHOT`, so I was not sure on what to use for the version. Shouldn't it be bumped to `1.1.2-SNAPSHOT`?

Sure, I can add that demo. But then I first need to figure out why the showcase is not running on Payara for me.

I personally have never needed to filter `b:message` components on severity. For the `b:growl` and `b:messages` I only use `severity` in combination with `globalOnly="true"`.

**Comment by jepsar** [comment]
Severity demo added in PR https://github.com/TheCoder4eu/BootsFacesWeb/pull/45

**Comment by stephanrauh** [comment]
So you've solved the Payara problem? And, of course, you're right: both library and showcase should be 1.1.2-SNAPSHOT. It's possible we're going to skip 1.1.2 in favor of 1.2, but currently, 1.1.2 is a good working title.

**Pull request merged**
